### ISSUE TITLE
'Startx' Crashes in Virtualization

### ISSUE THREAD

**Issue by AwlsomeAlex** [codyd51/axle#23]
Hello, I was using this Operating System in Virtualbox and it appears something similar to #21 also happens inside a Virtualbox Virtual Environment. I'm not sure if it's the hardware that's affecting it or the virtualization settings, so I'll just post everything to make it easier. Also this is the v0.5-alpha release found on GitHub, not locally built. (But for some reason the Kernel calls itself Version 0.6.0 at boot?)

## How its replicated:
Well, when I simply boot the system, it goes into a shell perfectly, but when I type the 'startx' command it gives me the problem.

## System Specifications: 
CPU: Intel Core i5-4210U
Mobo: N/A (Not showing)
GPU: AMD Radeon R7 M260
RAM: 12GB DDR3
Disk: 500GB Samsung SSD 850 EVO
Model: Toshiba Satellite L50t-B
OS: Windows 10 Home 1607

### General:
Version: 5.1.14
Type|Version: Other|Other/Unknown
### System:
Base Memory: 128MB (512MB Tested)
Chipset: PIIX3
Pointing Device: PS/2 Mouse
Extended Features: (none)
Processor: 1 CPU (PAE/NX Disabled)
### Display:
Video Memory: 32MB
### Audio:
Windows DirectSound (ICH AC97)
### Network:
(Disabled)
### USB:
(Disabled)

### Kernel Initialization Error:
Weird enough, I just realized the Kernel gave me an error stating:
`[ERROR Unhandled ISR: 3]`
if that helps.
### 'Startx' Error + Crash:
Then this shows up once 'Startx' is called:
https://postimg.org/image/qjesxsevn/
And the system crashes, with VirtualBox telling me its dead.

I hope this is enough information to help, if you need anymore I'll be able to provide it, but amazing job in the project, I really like how Hobbyist Operating Systems are coming back to life. Good Luck!
- AwlsomeAlex

**Comment by codyd51** [comment]
Hi!

As with issue #21, this is simply an exemplary bug report. I sincerely hope everyone can take an example from you two, it's really nice to have people who are able to lay out all the necessary details without being prompted!

I've been working today on a new version of axle which uses GRUB to boot directly into a high-resolution graphics mode (preferably 1024x768x24, though GRUB should fall back on whatever's available). I've ported axle's printing/shell to use this new system. 
[This](https://github.com/codyd51/axle/files/715509/axle.iso.zip) is an (extremely alpha!) ISO of this. Would you be able to see if this version sets the graphics mode correctly?

As for the kernel version number, those are just some arbitrary numbers I chose, don't worry that they don't match up :] I'll try to keep them consistent from now on, however.

The unhandled ISR is intentional as a ways of ensuring interrupts are being caught correctly.

Thanks for your kind words! :-) I'm really excited that people are checking out axle.

**Comment by AwlsomeAlex** [comment]
Thanks, I too am a programmer (A script-kiddie compared to you) but one thing I find aggravating is not enough information being given for debugging. 

I can confirm it sets the graphics mode correctly (in VirtualBox), however, it is blurry and stretched, but that can be as expected due to the early implementation of higher resolutions requiring new fonts and such. In QEMU on the other hand, when `startx` is launched, it is very distorted, but still, something that will be implemented, but it did switch to a higher resolution with no problem.

Also, I would also like to ask while I'm at it, where did you get the resources/knowledge for Operating System development, I am extremely interested in it but don't know where to start. Like should I read some Operating System Theory books? Learn C the hard way? Assembly books? Or like a specific online class/guide/tutorial?

**Comment by codyd51** [comment]
Perfect, that screenshot is exactly what I was hoping for! I've implemented automatic font scaling based on boot resolution in an earlier commit today which should improve the look a bit.

A strong understanding of C is paramount, as is a basic understanding of what a kernel is/does. Past that, wiki.osdev.org is an incredible resource and I've learned a ton from there. Personally, I haven't read physical books on any sort of development, I'm more of a learn-by-doer. As far as classes, I'm a freshman in college so I'm not eligible to take courses like that yet.

As this issue seems to be resolved, I'm going to close it now.
